name: Python Backend Tests

on:
  push:
    branches: [ main, develop, 'claude/**' ]
    paths:
      - 'backend/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/python-tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    name: Python ${{ matrix.python-version }} Backend Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio
      working-directory: ./backend

    - name: Run tests
      run: pytest tests/ -v --tb=short
      working-directory: ./backend
      env:
        PYTHONPATH: ${{ github.workspace }}/backend

    - name: Generate coverage report
      if: matrix.python-version == '3.10'
      run: pytest tests/ --cov=. --cov-report=xml
      working-directory: ./backend
      env:
        PYTHONPATH: ${{ github.workspace }}/backend

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.10'
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage.xml
        flags: python
        name: python-coverage
